# First install pre-commit:
#   pre-commit install
# Update this file:
#   pre-commit autoupdate
# Apply to all files without committing:
#   pre-commit run --all-files

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-json
    -   id: check-added-large-files
