name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose --version
      working-directory: .

    - name: Log in to Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        echo "//docker.io/v1/" > ~/.docker/config.json
        echo "{\"auths\":{\"docker.io\":{\"auth\":\"$(echo -n "$DOCKER_HUB_USERNAME:$DOCKER_HUB_TOKEN" | base64)\"}}}" >> ~/.docker/config.json
        docker-compose build
        docker-compose push
