name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose --version

    - name: Build and push Backend image
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/istif-backend
      run: |
        docker-compose -f docker-compose.yml build backend
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker-compose -f docker-compose.yml push backend

    - name: Build and push Frontend image
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/istif-frontend
      run: |
        docker-compose -f docker-compose.yml build frontend
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker-compose -f docker-compose.yml push frontend
