name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Backend image
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/istif
        IMAGE_TAG: istif-backend-latest
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG ./istif_backend
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Build and push Frontend image
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/istif
        IMAGE_TAG: istif-frontend-latest
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG ./istif_frontend
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push $IMAGE_NAME:$IMAGE_TAG
